@extends('company.layouts.app')
@section('title', __('company.team.title'))
@section('content')
@php($canManage = in_array('members.manage', $companyMembership['permissions'], true))
@php($canInvite = in_array('members.invite', $companyMembership['permissions'], true))
<div class="mx-auto max-w-6xl"><h1 class="text-3xl font-bold">{{ __('company.team.title') }}</h1><p class="panel-muted mt-2">{{ __('company.team.subtitle') }}</p>
@if (session('company_invite_url'))<div class="company-feedback-success mt-6 rounded-xl border p-4"><p class="text-sm font-semibold">{{ __('company.team.invite_link') }}</p><input class="panel-input-block mt-2" readonly value="{{ session('company_invite_url') }}"></div>@endif
@if ($canInvite)<form class="panel-card mt-7 grid gap-4 p-5 md:grid-cols-[1fr_220px_auto]" method="post" action="{{ route('company.team.invite') }}">@csrf<input class="panel-input" type="email" name="email" placeholder="ekip@kurum.com" required><select class="panel-input" name="role">@foreach(['admin','recruiter','hiring_manager','viewer'] as $role)<option value="{{ $role }}">{{ __('company.roles.'.$role) }}</option>@endforeach</select><button class="company-btn-primary">{{ __('company.team.invite') }}</button></form>@endif
<section class="mt-6 space-y-3">@foreach($team['members'] as $member)<article class="panel-card flex flex-wrap items-center justify-between gap-4 p-5"><div><p class="font-semibold">{{ $member['full_name'] }}</p><p class="panel-muted text-sm">{{ $member['email'] }}</p></div>@if($canManage && $member['user_id'] !== ($companyUser['id']??null))<form class="flex gap-2" method="post" action="{{ route('company.team.update',$member['membership_id']) }}">@csrf @method('PATCH')<select class="panel-input" name="role">@foreach(['owner','admin','recruiter','hiring_manager','viewer'] as $role)<option value="{{ $role }}" @selected($member['role']===$role)>{{ __('company.roles.'.$role) }}</option>@endforeach</select><select class="panel-input" name="status"><option value="active" @selected($member['status']==='active')>{{ __('company.status.active') }}</option><option value="suspended" @selected($member['status']==='suspended')>{{ __('company.status.suspended') }}</option></select><button class="company-btn-secondary">{{ __('company.team.save') }}</button></form>@else<span class="text-sm text-slate-500">{{ __('company.roles.'.$member['role']) }}</span>@endif</article>@endforeach</section>
@if(count($team['pending_invitations']))<h2 class="mt-8 text-lg font-semibold">{{ __('company.team.pending') }}</h2><div class="mt-3 space-y-2">@foreach($team['pending_invitations'] as $invite)<div class="panel-card flex justify-between p-4 text-sm"><span>{{ $invite['email'] }}</span><span>{{ __('company.roles.'.$invite['role']) }}</span></div>@endforeach</div>@endif
</div>
@endsection
